### ISSUE TITLE
Doesnt run the first time?

### ISSUE THREAD

**Issue by MACscr** [LeanAdmin/console-log#1]
Im trying to use them within livewire components. Lets say im using full page components where they are loaded as livewire routes. The consoles logs never fire, but if I rerender the component or another component after that page load, then the logs fire off. Any suggestions? is it because the package isnt loading before the page load happens?

**Comment by stancl** [comment]
Must be an issue with your layout or something, it works for me without issues.

**Comment by MACscr** [comment]
Let me elaborate a bit with some code. In my component, on first render, neither of these console commands run until it rerendered.

```
    public function mount(Contact $contact)
    {
        $this->consoleLog('running contacts.index mount()');
        logger('contacts->mount() just ran');
    }

    public function render()
    {
        $this->consoleLog('running contacts.index render()');
        logger('contacts->render() just ran');

        return view('contacts.index');
    }
```
